# Generated by Django 3.0.6 on 2020-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=30)),
                ('blog_details', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('blog_author', models.CharField(max_length=20)),
            ],
        ),
    ]
